alteret/src/Entity/Alteret.php
<?php

namespace App\Entity;

use App\Repository\AlteretRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: AlteretRepository::class)]
class Alteret
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Quantite = null;

    #[ORM\Column]
    private ?int $Prix = null;

    #[ORM\Column(length: 255)]
    private ?string $Photo = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Modele = null;



    #[ORM\OneToMany(mappedBy: 'Alteret', targetEntity: Commande::class)]
    private Collection $commandes ;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): static
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(string $Photo): static
    {
        $this->Photo = $Photo;

        return $this;
    }
    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->Modele;
    }

    public function setModele(string $Modele): static
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setAlteret($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // Set the owning side to null (unless already changed)
            if ($commande->getAlteret() === $this) {
                $commande->setAlteret(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->Modele; // Use the correct property name
    }
    
}

alteret/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AlteretRepository;
use App\Entity\Alteret;
use App\Entity\Commande;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(AlteretRepository $lr): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'Alterets' => $lr->findAll(),
        ]);
    }
    #[Route('/item/{id}', name: 'app_item')]
    public function indexitem(AlteretRepository $lr, int $id): Response
    {
        $Alteret = $lr->find($id);
        if (!$Alteret) {
            throw $this->createNotFoundException('Produit non trouvé.');
        }
        return $this->render('default/item.html.twig', [
            'Alteret' => $Alteret, 
        ]);
    }




#[Route('/achat/{id}', name: 'app_default_achat', methods: ['POST'])]
// #[IsGranted('ROLE_USER')]
    public function acheter(
        Alteret $Alteret,
        EntityManagerInterface $entityManager,
        Security $security
    ): Response {
        if ($Alteret->getQuantite() <= 0) {
            $this->addFlash('danger', 'Cette Alteret est indisponible.');
            return $this->redirectToRoute('app_default');
        }

        $user = $security->getUser();
        if (!$user) {
            $this->addFlash('danger', 'Vous devez être connecté pour effectuer cet achat.');
            return $this->redirectToRoute('app_login');
        }

        $commande = new Commande();
        $commande->setAlteret($Alteret);
        $commande->setQuantite(1); 
        $commande->setPrix($Alteret->getPrix());
        $commande->setDate(new \DateTime());

        $commande->setUser($user);

        $Alteret->setQuantite($Alteret->getQuantite() - 1);

        $entityManager->persist($commande);
        $entityManager->persist($Alteret);
        $entityManager->flush();

    $this->addFlash('success', 'Commande effectuée avec succès.');
    return $this->redirectToRoute('app_default', ['success' => 1]);
    }
}

alteret/templates/default/index.html.twig
{% extends 'Users.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}


<section id="hero">
    <div class="swiper slideshow">
      <div class="swiper-wrapper">
        {# <div class="swiper-slide" style="background-image:url("{{asset('assets/images/banner1.jpg')}}");"> #}
         <div class="swiper-slide" style="background-image: url(&quot;{{ asset('assets/images/banner1.jpg') }}&quot;);">

          <div class="container-fluid px-5 padding-large">
            <div class="row">
              <div class="text-center" data-aos="fade-up" data-aos-delay="300">
                <h2 class="display-1 text-uppercase text-white mt-3">Enhance Your Body</h2>
                <p class="text-capitalize text-white fs-5 mb-4">Elevate your muscles with new equipments</p>
                <a href="#best-seller" class="btn btn-outline-light btn-wrap">
                  Start Shopping
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide" style="background-image: url(&quot;{{ asset('assets/images/banner2.jpg') }}&quot;);">

        {# <div class="swiper-slide" style="background-image:url("{{asset('assets/images/banner2.jpg')}}");"> #}
          <div class="container-fluid px-5 padding-large">
            <div class="row">
              <div class="text-center" data-aos="fade-up" data-aos-delay="600">
                <h2 class="display-1 text-uppercase text-white mt-3">Enhance your body</h2>
                <p class="text-capitalize text-white fs-5 mb-4">Elevate your muscles with new equipments</p>
                <a href="#best-seller" class="btn btn-outline-light btn-wrap">
                  Start Shopping
                </a>
              </div>
            </div>
          </div>
        </div>
        {# <div class="swiper-slide" style="background-image: url(&quot;{{ asset('assets/images/banner3.jpg') }}&quot;);">

          <div class="container-fluid px-5 padding-large">
            <div class="row">
              <div class="text-center" data-aos="fade-up" data-aos-delay="900">
                <h2 class="display-1 text-uppercase text-white mt-3">Enhance your body</h2>
                <p class="text-capitalize text-white fs-5 mb-4">Elevate your muscles with new equipments</p>
                <a href="#" class="btn btn-outline-light btn-wrap">
                  Start Shopping
                </a>
              </div>
            </div>
          </div>
        </div> #}
      </div>
      <div class="swiper-pagination swiper-pagination-slideshow "></div>

    </div>
  </section>

  <section class="logo-bar">
    <div class="container-fluid px-3 px-md-5 padding-medium">
      <div class="row ">
        <div class="logo-content d-flex flex-wrap justify-content-between">
          <a href="#"> <img src="{{asset('assets/images/logo1.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>
          <a href="#"> <img src="{{asset('assets/images/logo2.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>
          <a href="#"> <img src="{{asset('assets/images/logo3.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>
          <a href="#"> <img src="{{asset('assets/images/logo4.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>
          <a href="#"> <img src="{{asset('assets/images/logo5.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>
          <a href="#"> <img src="{{asset('assets/images/logo2.png')}}" alt="logo" class="logo-image img-fluid my-3"> </a>

        </div>
      </div>
    </div>
  </section>

  <section id="category" class="">
    <div class="container-fluid px-3 px-md-5">
      <div class="row">

        <div class="col-md-4 position-relative">
          <div class="z-1 position-absolute bottom-0 start-0 m-3 m-lg-5 ps-4 text-white">
            <h3 class="text-light text-uppercase">Kettlebells</h3>
          </div>
          <div class="image-holder zoom-effect">
            <a href="single-post.html">
              <img src="{{asset('assets/images/category1.jpg')}}" alt="img" class="post-image img-fluid">
            </a>
          </div>
        </div>
        <div class="col-md-4 position-relative ">
          <div class="z-1 position-absolute bottom-0 start-0 m-3 m-lg-5 ps-4 text-white">
            <h3 class="text-light text-uppercase">Dumbbells</h3>
          </div>
          <div class="image-holder zoom-effect">
            <a href="single-post.html">
              <img src="{{asset('assets/images/category3.jpg')}}" alt="img" class="post-image img-fluid">
            </a>
          </div>
        </div>
        <div class="col-md-4 position-relative">
          <div class="z-1 position-absolute bottom-0 start-0 m-3 m-lg-5 ps-4 text-white">
            <h3 class="text-light text-uppercase">Workout supplements</h3>
          </div>
          <div class="image-holder zoom-effect">
            <a href="single-post.html">
              <img src="{{asset('assets/images/category2.jpg')}}" alt="img" class="post-image img-fluid">
            </a>
          </div>
        </div>

      </div>
    </div>
  </section>

  
<section id="best-seller" class="product-store">
    <div class="container-fluid px-3 px-md-5 padding-medium">
      <h2 class="display-5 fw-light text-uppercase text-center">Best Sellers</h2>
      <p class="text-center mb-4">Elevate your style with our best sellers</p>
      <div class="row">
        {% for Alteret in Alterets %}
        <div class="col-md-6 col-lg-3 my-4">
          <div class="product-item">
            <div class="image-holder" style="width: 20em; height: 20em;">
              <img src="{{ asset('uploads/images/' ~ Alteret.Photo) }}"   alt="Books" class="product-image img-fluid">
            </div>
            <div class="cart-concern">
              <div class="cart-button d-flex justify-content-between align-items-center">
                <a href="{{ path('app_item', {'id': Alteret.id}) }}" class="view-btn mt-1">
                  <i class="icon icon-screen-full"></i>
                </a>
                {# <a href="#" class="wishlist-btn mt-1">
                  <i class="icon icon-heart"></i>
                </a> #}
              </div>
            </div>
            <div class="product-detail d-flex justify-content-between align-items-center mt-2">
              <h5 class="product-title mb-0">
                <a href="single-product.html">{{ Alteret.Modele }}</a>
              </h5>
              <p class="m-0 fs-5 fw-normal">{{ Alteret.Quantite }} Produits</p>
              <p class="m-0 fs-5 fw-normal">{{ Alteret.Prix }}DT</p>

            </div>
          </div>
        </div>
        {% endfor %}

   <section id="register" style='background-image: url("{{ asset('assets/images/background-img.jpg') }}");'> 
    <div class="container padding-medium">
      <div class="row banner-content align-items-center padding-medium">
        <div class="col-md-6">
          <h2 class="display-2 text-white mt-3">Get <span> <em>20% OFF</em> </span> on your first purchase</h2>
          <p class="text-white mb-4">Enter your email and never miss any offers</p>
        </div>
        <div class="col-md-4 offset-md-1">
          <form method="POST" action="/send-code">
            <div class="mb-3">
              <input type="email" class="form-control form-control-lg rounded-3 text-center" name="email" id="email"
                placeholder="Enter Your Email Address">
            </div>
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-dark btn-lg rounded-3">Get Now</button>
            </div>
          </form>
        </div>

      </div>
    </div>
  </section>

  <br><br>

  <div id="blog">
    <div class="container-fluid px-3 px-md-5 padding-medium pt-0">
      <div class="section-header d-md-flex justify-content-between align-items-center mb-3">
        <h2 class="display-5 fw-light text-uppercase">Recent Blog Post</h2>
        <div>
          <a href="blog.html" class="btn btn-outline-dark py-3 px-5">
            Read Blog</a>
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 my-4">
          <div class="z-1 position-absolute m-2 px-3 pt-1">
            <h2 class="text-white display-4 m-0">20<span class="fs-4">FEB</span> </h2>
          </div>
          <div class="card position-relative ">
            <a href="single-post.html"><img src="{{asset('assets/images/blog5.jpg')}}" class="img-fluid" alt="image"></a>
            <div class="card-body p-0">
              <a href="single-post.html">
                <h3 class="card-title pt-4 pb-3 m-0">10 new workout routines for this summer</h3>
              </a>

              <div class="card-text">
                <p class="blog-paragraph fs-6">At the core of our practice is the idea that cities are the incubators of
                  our greatest
                  achievements, and the best hope for a sustainable future. This is the best way to style the product in
                  your own wat.</p>

              </div>

            </div>
          </div>
        </div>
        <div class="col-md-4 my-4">
          <div class="z-1 position-absolute m-2 px-3 pt-1">
            <h2 class="text-white display-4 m-0">21<span class="fs-4">FEB</span> </h2>

          </div>
          <div class="card position-relative ">
            <a href="single-post.html"><img src="{{asset('assets/images/blog2.jpg')}}" class="img-fluid" alt="image"></a>
            <div class="card-body p-0">
              <a href="single-post.html">
                <h3 class="card-title pt-4 pb-3 m-0">How to get good equiments in budget</h3>
              </a>

              <div class="card-text">
                <p class="blog-paragraph fs-6">At the core of our practice is the idea that cities are the incubators of
                  our greatest
                  achievements, and the best hope for a sustainable future. This is the best way to style the product in
                  your own wat.</p>

              </div>

            </div>
          </div>
        </div>
        <div class="col-md-4 my-4">
          <div class="z-1 position-absolute m-2 px-3 pt-1">
            <h2 class="text-white display-4 m-0">22<span class="fs-4">FEB</span> </h2>

          </div>
          <div class="card position-relative">
            <a href="single-post.html"><img src="{{asset('assets/images/blog1.jpg')}}" class="img-fluid" alt="image"></a>
            <div class="card-body p-0">
              <a href="single-post.html">
                <h3 class="card-title pt-4 pb-3 m-0">Best workout tips from experts</h3>
              </a>

              <div class="card-text">
                <p class="blog-paragraph fs-6">At the core of our practice is the idea that cities are the incubators of
                  our greatest
                  achievements, and the best hope for a sustainable future. This is the best way to style the product in
                  your own wat.</p>

              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section id="service" class="bg-light padding-medium">
    <div class="container">
      <div class="row g-md-5 pt-4">
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-black display-4" icon="ci:shopping-cart-02"></iconify-icon>
            </div>
            <h4 class=" text-uppercase py-3 m-0">Free Delivery</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Lorem ipsum dolor sit amet, consectetur adipi elit.</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-black display-4" icon="tdesign:secured"></iconify-icon>
            </div>
            <h4 class=" text-uppercase py-3 m-0">100% secure payment</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Lorem ipsum dolor sit amet, consectetur adipi elit.</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-black display-4" icon="la:award"></iconify-icon>
            </div>
            <h4 class=" text-uppercase py-3 m-0">Quality guarantee</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Lorem ipsum dolor sit amet, consectetur adipi elit.</p>
              </div>
          </div>
        </div>
        <div class="col-md-3 my-3">
          <div class="card">
            <div>
              <iconify-icon class="service-icon text-black display-4" icon="solar:dollar-outline"></iconify-icon>
            </div>
            <h4 class=" text-uppercase py-3 m-0">Daily Offer</h3>
              <div class="card-text">
                <p class="blog-paragraph fs-6">Lorem ipsum dolor sit amet, consectetur adipi elit.</p>
              </div>
          </div>
        </div>

      </div>
    </div>
  </section>
{% endblock %}

alteret/templates/default/item.html.twig
 {% extends 'Users.html.twig' %}
    {% block stylesheet %}

<nav class="navbar navbar-expand-lg navbar-light bg-black">
    <div class="container px-4 px-lg-5">
        <!-- Logo à gauche -->
        <a class="navbar-brand" href="index.html">
            <img src="{{ asset('assets/images/logo.png') }}" alt="logo" class="img-fluid" style="max-height: 50px;">
        </a>
        <!-- Bouton pour les menus en version mobile -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Contenu du menu -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app_default')}}">Home</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% endblock %}

{% block body %} 

  <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ asset('uploads/images/' ~ Alteret.photo) }}"  alt="..." /></div>
                    <div class="col-md-6">
                        <div class="small mb-1">{{Alteret.quantite}} Unité</div>
                        <h1 class="display-5 fw-bolder">{{Alteret.Modele}}</h1>
                        <div class="fs-5 mb-5">
                            <span class="text-decoration-line-through">{{Alteret.prix+25}}DT</span>
                            <span>{{Alteret.prix}}DT</span>
                        </div>
                        <p class="lead">{{Alteret.Description}}</p>
                         <div class="d-flex">
                    {% if Alteret.quantite > 0 %}
                        <form action="{{ path('app_default_achat', {id: Alteret.id}) }}" method="post">
                            <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                                <i class="bi-cart-fill me-1"></i>
                                Acheter
                            </button>
                        </form>


                    {% else %}
                        <button class="btn btn-outline-dark flex-shrink-0" type="button" disabled>
                            <i class="bi-cart-fill me-1"></i>
                            Indisponible
                        </button>
                    {% endif %}
                </div>
                    </div>
                </div>
            </div>
        </section>   

  
        {% endblock %}